package cn.et.works.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import cn.et.works.entity.Dept1;
import cn.et.works.entity.Dept1Example;


@Mapper
public interface Dept1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @SelectProvider(type=Dept1SqlProvider.class, method="countByExample")
    long countByExample(Dept1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @DeleteProvider(type=Dept1SqlProvider.class, method="deleteByExample")
    int deleteByExample(Dept1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @Delete({
        "delete from dept1",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @Insert({
        "insert into dept1 (id, dname, ",
        "pid)",
        "values (#{id,jdbcType=INTEGER}, #{dname,jdbcType=VARCHAR}, ",
        "#{pid,jdbcType=INTEGER})"
    })
    int insert(Dept1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @InsertProvider(type=Dept1SqlProvider.class, method="insertSelective")
    int insertSelective(Dept1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @SelectProvider(type=Dept1SqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="dname", property="dname", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER)
    })
    List<Dept1> selectByExampleWithRowbounds(Dept1Example example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @SelectProvider(type=Dept1SqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="dname", property="dname", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER)
    })
    List<Dept1> selectByExample(Dept1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @Select({
        "select",
        "id, dname, pid",
        "from dept1",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="dname", property="dname", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER)
    })
    Dept1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @UpdateProvider(type=Dept1SqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Dept1 record, @Param("example") Dept1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @UpdateProvider(type=Dept1SqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Dept1 record, @Param("example") Dept1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @UpdateProvider(type=Dept1SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Dept1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbg.generated Tue Dec 12 20:48:24 CST 2017
     */
    @Update({
        "update dept1",
        "set dname = #{dname,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Dept1 record);
}