package cn.et.works.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import cn.et.works.entity.Emp2;
import cn.et.works.entity.Emp2Example;

@Mapper
public interface Emp2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @SelectProvider(type=Emp2SqlProvider.class, method="countByExample")
    int countByExample(Emp2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @DeleteProvider(type=Emp2SqlProvider.class, method="deleteByExample")
    int deleteByExample(Emp2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @Delete({
        "delete from emp2",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @Insert({
        "insert into emp2 (id, ename, ",
        "sal, deptid)",
        "values (#{id,jdbcType=INTEGER}, #{ename,jdbcType=VARCHAR}, ",
        "#{sal,jdbcType=INTEGER}, #{deptid,jdbcType=INTEGER})"
    })
    int insert(Emp2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @InsertProvider(type=Emp2SqlProvider.class, method="insertSelective")
    int insertSelective(Emp2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @SelectProvider(type=Emp2SqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ename", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="sal", property="sal", jdbcType=JdbcType.INTEGER),
        @Result(column="deptid", property="deptid", jdbcType=JdbcType.INTEGER)
    })
    List<Emp2> selectByExampleWithRowbounds(Emp2Example example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @SelectProvider(type=Emp2SqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ename", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="sal", property="sal", jdbcType=JdbcType.INTEGER),
        @Result(column="deptid", property="deptid", jdbcType=JdbcType.INTEGER)
    })
    List<Emp2> selectByExample(Emp2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @Select({
        "select",
        "id, ename, sal, deptid",
        "from emp2",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ename", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="sal", property="sal", jdbcType=JdbcType.INTEGER),
        @Result(column="deptid", property="deptid", jdbcType=JdbcType.INTEGER)
    })
    Emp2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @UpdateProvider(type=Emp2SqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Emp2 record, @Param("example") Emp2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @UpdateProvider(type=Emp2SqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Emp2 record, @Param("example") Emp2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @UpdateProvider(type=Emp2SqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Emp2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp2
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    @Update({
        "update emp2",
        "set ename = #{ename,jdbcType=VARCHAR},",
          "sal = #{sal,jdbcType=INTEGER},",
          "deptid = #{deptid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Emp2 record);
}