package cn.et.works.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import cn.et.works.entity.Emp;
import cn.et.works.entity.EmpExample;


@Mapper
public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @SelectProvider(type=EmpSqlProvider.class, method="countByExample")
    int countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @DeleteProvider(type=EmpSqlProvider.class, method="deleteByExample")
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @Delete({
        "delete from emp",
        "where empno = #{empno,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer empno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @Insert({
        "insert into emp (empno, ename, ",
        "job, mgr, hiredate, ",
        "sal, deptno)",
        "values (#{empno,jdbcType=INTEGER}, #{ename,jdbcType=VARCHAR}, ",
        "#{job,jdbcType=VARCHAR}, #{mgr,jdbcType=INTEGER}, #{hiredate,jdbcType=TIMESTAMP}, ",
        "#{sal,jdbcType=INTEGER}, #{deptno,jdbcType=INTEGER})"
    })
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @InsertProvider(type=EmpSqlProvider.class, method="insertSelective")
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @SelectProvider(type=EmpSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="empno", property="empno", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ename", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="job", property="job", jdbcType=JdbcType.VARCHAR),
        @Result(column="mgr", property="mgr", jdbcType=JdbcType.INTEGER),
        @Result(column="hiredate", property="hiredate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="sal", property="sal", jdbcType=JdbcType.INTEGER),
        @Result(column="deptno", property="deptno", jdbcType=JdbcType.INTEGER)
    })
    List<Emp> selectByExampleWithRowbounds(EmpExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @SelectProvider(type=EmpSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="empno", property="empno", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ename", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="job", property="job", jdbcType=JdbcType.VARCHAR),
        @Result(column="mgr", property="mgr", jdbcType=JdbcType.INTEGER),
        @Result(column="hiredate", property="hiredate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="sal", property="sal", jdbcType=JdbcType.INTEGER),
        @Result(column="deptno", property="deptno", jdbcType=JdbcType.INTEGER)
    })
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @Select({
        "select",
        "empno, ename, job, mgr, hiredate, sal, deptno",
        "from emp",
        "where empno = #{empno,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="empno", property="empno", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ename", property="ename", jdbcType=JdbcType.VARCHAR),
        @Result(column="job", property="job", jdbcType=JdbcType.VARCHAR),
        @Result(column="mgr", property="mgr", jdbcType=JdbcType.INTEGER),
        @Result(column="hiredate", property="hiredate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="sal", property="sal", jdbcType=JdbcType.INTEGER),
        @Result(column="deptno", property="deptno", jdbcType=JdbcType.INTEGER)
    })
    Emp selectByPrimaryKey(Integer empno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @UpdateProvider(type=EmpSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @UpdateProvider(type=EmpSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @UpdateProvider(type=EmpSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    @Update({
        "update emp",
        "set ename = #{ename,jdbcType=VARCHAR},",
          "job = #{job,jdbcType=VARCHAR},",
          "mgr = #{mgr,jdbcType=INTEGER},",
          "hiredate = #{hiredate,jdbcType=TIMESTAMP},",
          "sal = #{sal,jdbcType=INTEGER},",
          "deptno = #{deptno,jdbcType=INTEGER}",
        "where empno = #{empno,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Emp record);
}