package cn.et.works.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.jdbc.SQL;

import cn.et.works.entity.Emp;
import cn.et.works.entity.EmpExample;
import cn.et.works.entity.EmpExample.Criteria;
import cn.et.works.entity.EmpExample.Criterion;



public class EmpSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    public String countByExample(EmpExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("emp");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    public String deleteByExample(EmpExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("emp");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    public String insertSelective(Emp record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("emp");
        
        if (record.getEmpno() != null) {
            sql.VALUES("empno", "#{empno,jdbcType=INTEGER}");
        }
        
        if (record.getEname() != null) {
            sql.VALUES("ename", "#{ename,jdbcType=VARCHAR}");
        }
        
        if (record.getJob() != null) {
            sql.VALUES("job", "#{job,jdbcType=VARCHAR}");
        }
        
        if (record.getMgr() != null) {
            sql.VALUES("mgr", "#{mgr,jdbcType=INTEGER}");
        }
        
        if (record.getHiredate() != null) {
            sql.VALUES("hiredate", "#{hiredate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSal() != null) {
            sql.VALUES("sal", "#{sal,jdbcType=INTEGER}");
        }
        
        if (record.getDeptno() != null) {
            sql.VALUES("deptno", "#{deptno,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    public String selectByExample(EmpExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("empno");
        } else {
            sql.SELECT("empno");
        }
        sql.SELECT("ename");
        sql.SELECT("job");
        sql.SELECT("mgr");
        sql.SELECT("hiredate");
        sql.SELECT("sal");
        sql.SELECT("deptno");
        sql.FROM("emp");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Emp record = (Emp) parameter.get("record");
        EmpExample example = (EmpExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("emp");
        
        if (record.getEmpno() != null) {
            sql.SET("empno = #{record.empno,jdbcType=INTEGER}");
        }
        
        if (record.getEname() != null) {
            sql.SET("ename = #{record.ename,jdbcType=VARCHAR}");
        }
        
        if (record.getJob() != null) {
            sql.SET("job = #{record.job,jdbcType=VARCHAR}");
        }
        
        if (record.getMgr() != null) {
            sql.SET("mgr = #{record.mgr,jdbcType=INTEGER}");
        }
        
        if (record.getHiredate() != null) {
            sql.SET("hiredate = #{record.hiredate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSal() != null) {
            sql.SET("sal = #{record.sal,jdbcType=INTEGER}");
        }
        
        if (record.getDeptno() != null) {
            sql.SET("deptno = #{record.deptno,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("emp");
        
        sql.SET("empno = #{record.empno,jdbcType=INTEGER}");
        sql.SET("ename = #{record.ename,jdbcType=VARCHAR}");
        sql.SET("job = #{record.job,jdbcType=VARCHAR}");
        sql.SET("mgr = #{record.mgr,jdbcType=INTEGER}");
        sql.SET("hiredate = #{record.hiredate,jdbcType=TIMESTAMP}");
        sql.SET("sal = #{record.sal,jdbcType=INTEGER}");
        sql.SET("deptno = #{record.deptno,jdbcType=INTEGER}");
        
        EmpExample example = (EmpExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    public String updateByPrimaryKeySelective(Emp record) {
        SQL sql = new SQL();
        sql.UPDATE("emp");
        
        if (record.getEname() != null) {
            sql.SET("ename = #{ename,jdbcType=VARCHAR}");
        }
        
        if (record.getJob() != null) {
            sql.SET("job = #{job,jdbcType=VARCHAR}");
        }
        
        if (record.getMgr() != null) {
            sql.SET("mgr = #{mgr,jdbcType=INTEGER}");
        }
        
        if (record.getHiredate() != null) {
            sql.SET("hiredate = #{hiredate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getSal() != null) {
            sql.SET("sal = #{sal,jdbcType=INTEGER}");
        }
        
        if (record.getDeptno() != null) {
            sql.SET("deptno = #{deptno,jdbcType=INTEGER}");
        }
        
        sql.WHERE("empno = #{empno,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbg.generated Fri Dec 08 19:23:52 CST 2017
     */
    protected void applyWhere(SQL sql, EmpExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}