package cn.et.works.entity;

public class Emp2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp2.id
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp2.ename
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp2.sal
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    private Integer sal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp2.deptid
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    private Integer deptid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp2.id
     *
     * @return the value of emp2.id
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp2.id
     *
     * @param id the value for emp2.id
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp2.ename
     *
     * @return the value of emp2.ename
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp2.ename
     *
     * @param ename the value for emp2.ename
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp2.sal
     *
     * @return the value of emp2.sal
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    public Integer getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp2.sal
     *
     * @param sal the value for emp2.sal
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    public void setSal(Integer sal) {
        this.sal = sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp2.deptid
     *
     * @return the value of emp2.deptid
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp2.deptid
     *
     * @param deptid the value for emp2.deptid
     *
     * @mbg.generated Tue Dec 12 20:59:12 CST 2017
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }
}